CORRECOES = {
    "abito": "obito",
    "agressao fasica verbal": "agressao fisica verbal",
    "ameaaa": "ameaca",
    "apropriaaao indabita": "apropriacao indebita",
    "argaos acionados": "orgaos acionados",
    "atitude suspeita abordagem": "atitude suspeita",
    "avaria em equipamento patrima nio nao intencional": "avaria em equipamento patrimonio nao intencional",
    "averiguaaao comarcio ilegal": "averiguacao comercio ilegal",
    "averiguaaao cosedi": "averiguacao cosedi",
    "averiguaaao defesa civil": "averiguacao defesa civil",
    "banho em local impra3prio": "banho em local improprio",
    "calaonia": "calunia",
    "comarcio ambulante": "comercio ambulante",
    "construaao irregular": "construcao irregular",
    "corrupaao de menores": "corrupcao de menores",
    "crianaa perdida desaparecida": "crianca perdida desaparecida",
    "denaoncia de bomba": "denuncia de bomba",
    "depa3sito irregular": "deposito irregular",
    "desinteligaancia": "desinteligencia",
    "deslizamenton de terra": "deslizamento de terra",
    "desobediaancia": "desobediencia",
    "devoluaao de coisa achada": "devolucao de coisa achada",
    "difamaaao": "difamacao",
    "discriminaaao": "discriminacao",
    "distaorbio": "disturbio",
    "exploraaao de menores": "exploracao de menores",
    "extravio sonegaaao ou inutilizaaao de livro ou doc": "extravio sonegacao ou inutilizacao de livro ou doc",
    "falsidade ideola3gica falsa identidade": "falsidade ideologica falsa identidade",
    "fiscalizaaaes e orientaaaes": "fiscalizacoes e orientacoes",
    "fornecimento de bebida alcoa3lica a menores": "fornecimento de bebida alcoolica a menores",
    "homicadio": "homicidio",
    "impedimento ou perturbaaao de cerima nia funeraria": "impedimento ou perturbacao de cerimonia funeraria",
    "importunaaao ofensiva ao pudor": "importunacao ofensiva ao pudor",
    "importunaaaoa sexual": "importunacao sexual",
    "incaandio": "incendio",
    "incendio explosao em edificaaao": "incendio explosao em edificacao",
    "infiltraaao": "infiltracao",
    "injaoria": "injuria",
    "inundaaao enchente": "inundacao enchente",
    "manifestaaao": "manifestacao",
    "manipulaaao de explosivo": "manipulacao de explosivo",
    "notificaaao": "notificacao",
    "obstruaao da atividade policial": "obstrucao da atividade policial",
    "ocupaaao irregular": "ocupacao irregular",
    "orientaaao": "orientacao",
    "perseguiaao stalking": "perseguicao stalking",
    "perturbaaao do sossego": "perturbacao do sossego",
    "poluiaao visual ambiental": "poluicao visual ambiental",
    "prevaricaaao": "prevaricacao",
    "proteaao ao patrima nio": "protecao ao patrimonio",
    "quedas de objetos ou partes de construaaes": "quedas de objetos ou partes de construcoes",
    "queima a cau aberto": "queima a ceu aberto",
    "rachadura em edificaaao": "rachadura em edificacao",
    "receptaaao": "receptacao",
    "resistaancia": "resistencia",
    "roubo furto extravio recuperaaao apreensao de armas de fogo": "roubo furto extravio recuperacao apreensao de armas de fogo",
    "seqa14estro e carcere privado": "sequestro e carcere privado",
    "situaaao de risco": "situacao de risco",
    "substancia ilacita": "substancia ilicita",
    "substancia lacita": "substancia licita",
    "suicadio": "suicidio",
    "tentativa de homicadio": "tentativa de homicidio",
    "veaculo": "veiculo",
    "venda proibida de produtos especaficos a menores": "venda proibida de produtos especificos a menores",
    "verificaaao": "verificacao",
    "violaaao de medida protetiva lei maria da penha": "violacao de medida protetiva lei maria da penha",
    "violaaao de sepultura taomulo": "violacao de sepultura tumulo",
    "violaancia arbitraria": "violencia arbitraria",
    "escrito ou objeto obsceno panfletos pornograficos": "panfletagem pornografica",
}

CRIME_VIOLENTO = {
    "abandono de incapaz",
    "abuso de incapazes",
    "agressao fisica verbal",
    "ameaca",
    "arrastao",
    "atentado violento ao pudor",
    "constrangimento ilegal",
    "disparo de arma",
    "estupro",
    "extorsao",
    "homicidio",
    "importunacao ofensiva ao pudor",
    "importunacao sexual",
    "lesao corporal",
    "maus tratos a pessoas",
    "omissao de socorro",
    "perseguicao stalking",
    "posse sexual mediante fraude",
    "resistencia",
    "rixa",
    "roubo",
    "sequestro e carcere privado",
    "tentativa de homicidio",
    "vias de fato",
    "violacao de medida protetiva lei maria da penha",
    "violencia arbitraria",
    "roubo furto extravio recuperacao apreensao de armas de fogo"
}

ATENDIMENTO_OPERACIONAL_ASSISTENCIAL = {
    "aifu",
    "alarmes",
    "antecedentes criminais verificacao",
    "apoio",
    "atitude suspeita",
    "averiguacao",
    "averiguacao cosedi",
    "averiguacao defesa civil",
    "denuncia improcedente",
    "encaminhamento",
    "envenenamento",
    "escolta",
    "evento",
    "fiscalizacoes e orientacoes",
    "fundada suspeita abordagem",
    "abordagem",
    "verificacao",
    "vistoria",
    "voo drone gmc",
    "zeladoria urbana",
    "liberacao de pessoa presa apreendida por recusa no recebimento pela dp",
    "notificacao",
    "obito",
    "obito defesa civil",
    "orgaos acionados",
    "orientacao",
    "paciente usuario alterado",
    "patrulha maria da penha",
    "protecao ao patrimonio",
    "ronda",
    "saturacao",
    "suicidio",
}

ACIDENTE_TRANSITO = {
    "acidente de transito",
    "acidente viatura",
    "transito",
    "queda de aeronave",
    "veiculo",
}

ACIDENTE_NATURAL = {
    "abalo sismico",
    "alagamento",
    "animais",
    "ataque cao feroz",
    "ataque de insetos",
    "bueiro aberto sem tampa",
    "bueiro entupido",
    "deslizamento de terra",
    "enxurrada",
    "erosao",
    "inundacao enchente",
    "pragas animais",
    "poda de arvore",
    "poluicao visual ambiental",
    "queda de arvore",
    "queda de galho",
    "risco de queda de arvore",
    "risco de queda de galho",
    "rompimento de barragem",
}

CRIME_PATRIMONIAL = {
    "apropriacao indebita",
    "calote",
    "dano",
    "estelionato",
    "furto",
    "invasao",
    "receptacao",
    "retirada de invasao",
}

CRIME_ADMNISTRACAO_PUBLICA = {
    "abandono de funcao",
    "contrabando ou descaminho",
    "concussao",
    "corrupcao ativa",
    "desacato",
    "desobediencia",
    "fingir se funcionario publico",
    "obstrucao da atividade policial",
    "peculato",
    "prevaricacao",
    "recusar se identificar ao policial",
    "tentativa de suborno",
    "usar de uniforme ou distintivo de funcao publica que nao exerce",
}

CRIME_HONRA_DISCRIMINACAO = {
    "calunia",
    "difamacao",
    "discriminacao",
    "homofobia",
    "injuria",
    "racismo",
}

CRIME_CRIANCA_ADOLESCENTE = {
    "aliciamento de menor",
    "corrupcao de menores",
    "exploracao de menores",
    "fornecimento de bebida alcoolica a menores",
    "fuga de aluno interno",
    "menor gazeando aula",
    "menores abordando transeuntes",
    "seducao",
    "venda proibida de produtos especificos a menores",
}

CRIME_FRAUDE_DOCUMENTAL = {
    "extravio sonegacao ou inutilizacao de livro ou doc",
    "falsidade ideologica falsa identidade",
    "falsificacao de documento publico",
    "moeda falsa",
    "uso indevido do cartao transporte",
    "uso indevido do telefone publico",
}

CRIME_DROGAS_SUBSTANCIAS = {
    "embriaguez",
    "substancia ilicita",
    "substancia licita",
}

CRIME_ORDEM_PUBLICA = {
    "apologia de crime ou criminoso",
    "aterro irregular",
    "atos obscenos libidinosos",
    "averiguacao comercio ilegal",
    "crime ambiental",
    "comercio ambulante",
    "conduta inconveniente",
    "construcao irregular",
    "corte irregular de arvore",
    "deposito irregular",
    "descumprimento lei 15799 2021 covid 19",
    "desinteligencia",
    "disturbio",
    "favorecimento da prostituicao",
    "impedimento ou perturbacao de cerimonia funeraria",
    "incitacao ao crime",
    "charlatanismo",
    "jogo de azar",
    "maus tratos a animais",
    "mendigar por ociosidade ou cupidez",
    "manifestacao",
    "obstrucao de via",
    "ocupacao irregular",
    "panfletagem pornografica",
    "pesca em local proibido",
    "perturbacao do sossego",
    "porte ilegal",
    "prostituicao",
    "quadrilha ou bando",
    "rufianismo",
    "trote telefonico",
    "vadiagem",
    "vilipendio a cadaver",
    "violacao de sepultura tumulo",
    "banho em local improprio",
    "voo drone irregular",
}

RISCO_ESTRUTURAL = {
    "afundamento de piso",
    "desabamento",
    "desabamento de telhado cobertura",
    "infiltracao",
    "queda de fios de energia",
    "queda de muro",
    "queda de poste",
    "queda de revestimento de fachadas",
    "quedas de objetos ou partes de construcoes",
    "rachadura em edificacao",
    "risco de acidente a vida",
    "risco de acidente a vida defesa civil",
    "risco de desabamento desmoronamento",
    "risco de queda de fios de energia",
    "risco de queda de poste",
    "situacao de risco",
    "destelhamento",
}

EXPLOSIVOS_E_PRODUTOS_PERIGOSOS = {
    "denuncia de bomba",
    "explosao",
    "incendio",
    "incendio explosao em edificacao",
    "manipulacao de explosivo",
    "porte de artefato explosivo",
    "queima a ceu aberto",
    "risco de explosao",
    "vazamento ou derramamento de produto perigoso ou infectante",
}

PESSOAS_DESAPARECIDAS = {
    "afogamento",
    "crianca perdida desaparecida",
    "desaparecimento",
    "fuga de paciente",
}

MATERIAIS_OBJETOS = {
    "achado",
    "apreensao de materiais",
    "avaria em equipamento patrimonio nao intencional",
    "camera off line",
    "cameras de videomonitoramento",
    "devolucao de coisa achada",
    "extravio de documento",
    "extravio de equipamento",
    "fornecimento de lona",
    "material abandonado",
    "recolhimento de materiais",
}

INDETERMINADO = {"tentativa",}
