DEFAULT_DROP_COLUMNS = (
    "OCORRENCIA_CODIGO",
    "REGIONAL_FATO_NOME",
    "SECRETARIA_NOME",
    "SITUACAO_EQUIPE_DESCRICAO",
    "OCORRENCIA_DATA",
    "OPERACAO_DESCRICAO",
    "ORIGEM_CHAMADO_DESCRICAO",
    "SUBCATEGORIA1_DESCRICAO",
    "SUBCATEGORIA2_DESCRICAO",
    "SUBCATEGORIA3_DESCRICAO",
    "SUBCATEGORIA4_DESCRICAO",
    "SUBCATEGORIA5_DESCRICAO",
    "EQUIPAMENTO_URBANO_NOME",
)

COLUNAS_TEXTO = (
    "ATENDIMENTO_BAIRRO_NOME",
    "LOGRADOURO_NOME",
    "NATUREZA1_DESCRICAO",
    "NATUREZA2_DESCRICAO",
    "NATUREZA3_DESCRICAO",
    "NATUREZA4_DESCRICAO",
    "NATUREZA5_DESCRICAO",
    "SECRETARIA_SIGLA",
    "SERVICO_NOME",
    "NUMERO_PROTOCOLO_156",
)

TESTE = ("ATENDIMENTO_BAIRRO_NOME",)

COLUNAS_BINARIAS = (
    "FLAG_EQUIPAMENTO_URBANO", 
    "FLAG_FLAGRANTE",
    "NATUREZA1_DEFESA_CIVIL",
    "NATUREZA2_DEFESA_CIVIL",
    "NATUREZA3_DEFESA_CIVIL",
    "NATUREZA4_DEFESA_CIVIL",
    "NATUREZA5_DEFESA_CIVIL",
)

COLUNA_DIA_SEMANA = ("OCORRENCIA_DIA_SEMANA",)

COLUNA_MES = ("OCORRENCIA_MES",)

COLUNA_HORA = "OCORRENCIA_HORA"

COLUNA_BAIRRO = ("ATENDIMENTO_BAIRRO_NOME", )

COLUNA_NATUREZA_DESCRICAO = (
    "NATUREZA1_DESCRICAO",
    "NATUREZA2_DESCRICAO",
    "NATUREZA3_DESCRICAO",
    "NATUREZA4_DESCRICAO",
    "NATUREZA5_DESCRICAO"
)
